qtranslate_frontend.php

The arguments should be passed by value, not ref for:
- qtranxf_postsFilter (the_posts)
- qtranxf_pre_get_posts (pre_get_posts)
- qtranxf_excludeUntranslatedPostComments (comments_clauses)

fix warnings expected references in php7.1+

---

dev/slugs/admin/qtx_admin_slug.php

Since it's in the dev folder, this file probably doesn't actually get accessed -- I found this when running a script to preload opcache, which compiles every php file on my system. But hey I thought I'd send in a fix anyway! :smile:

Fixes PHP Parse error:  syntax error, unexpected ')'

---

CHANGELOG.md
README.md
qtranslate.php
qtranslate_core.php
qtranslate_utils.php
readme.txt

Following issue https://github.com/qtranslate/qtranslate-xt/issues/609 i think i found a reasonable solution to prevent these nasty API REST redirects:
- REST calls should never redirect! Added a check with `qtranxf_is_rest_request_expected` based on `rest_get_url_prefix`.
- REST calls should be fully deterministic! Updated `qtranxf_detect_language` : REST calls should ignore any front/admin cookie and any other weird language detection.
- new init action `qtranxf_rest_api_register_rewrites` for specific rewrite rules to handle the case i described  earlier, when the default language is hidden in the options, but asked in the request. Note to make it work you have to **flush your rewrite rules by saving the permalink structures** from the admin page!
More info in …

Fix no redirect allowed on API REST

---

admin/qtx_activation_hook.php
admin/qtx_admin.php
admin/qtx_update_gettext_db.php
qtranslate_core.php

Use of the strtotime function instead of time.
The strtotime function avoids errors by DST.

Using strtotime() instead of time() + $seconds

---

admin/qtx_configuration.php
qtranslate_core.php

This PR is in substitution of https://github.com/qtranslate/qtranslate-xt/pull/630. This concerns the option "Show alternative content", meant to display the _post content in alternative languages_ when there's no translation for the current language. But instead of adding a new option to remove a part of the message, this becomes the new behavior.
Currently when the "alt content" option is selected many things are shown:
- notice: "Sorry, this entry is only available in %LANG: ...", containing links to allow language switch.
- long message: "For the sake of convenience, the content is shown below [very long text...]"
- the post content in alternative language (default or next in order)
With this PR the goal is to **remove** entirely the second part ("For the sake of convenience...").
As …

Shorten message for alt content

---

qtranslate_hooks.php

I noticed that embedded content wasn't translated so I looked how it could be done and my file change is the way how I succeeded into doing just that. I'm not sure where it should be placed so I added it in the `qtranslate_hooks` file.
Example link:
https://example.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fexample.com%2Fpage%2F

Making embedded content translatable

---

admin/qtx_admin_utils.php

ACF post object titles not translated

---

admin/qtx_activation_hook.php
admin/qtx_admin.php
qtranslate.php
qtranslate_core.php
qtranslate_utils.php

These two utility functions are unnecessary, they are bloating the code and lead to confusions: 
- `qtranxf_plugin_dirname() -> qtranslate`
- `qtranxf_plugin_basename() -> qtranslate/qtranslate.php`
Using directly the basic functions make the code more readable. The legacy functions become deprecated.
- `qtranxf_plugin_dirname() -> dirname( QTRANSLATE_DIR )`
- `qtranxf_plugin_basename() ->  plugin_basename( QTRANSLATE_FILE )`
Code cleanup follows.

Refactor plugin dirname and basename

---

admin/qtx_admin_gutenberg.php

If opening an existing post and the excerpt isn't set then an exception is thrown.
The Exception that I got:
```
ErrorException: Undefined index: excerpt in file plugins/qtranslate-xt/admin/qtx_admin_gutenberg.php on line 188
Stack trace:
1. ErrorException-&gt;() plugins/qtranslate-xt/admin/qtx_admin_gutenberg.php:188
2. Themosis\Core\Bootstrap\ExceptionHandler-&gt;handleError() plugins/qtranslate-xt/admin/qtx_admin_gutenberg.php:188
3. QTX_Admin_Gutenberg-&gt;select_raw_response_language() plugins/qtranslate-xt/admin/qtx_admin_gutenberg.php:70
4. QTX_Admin_Gutenberg-&gt;rest_prepare() wp-includes/class-wp-hook.php:288
5. WP_Hook-&gt;apply_filters() wp-includes/plugin.php:206
6. apply_filters() wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:1688
7. …
```

Fix excerpt not set on post edit in Gutenberg

---

modules/woo-commerce/qwc-admin.php

When viewing WooCommerce orders from the admin side, the name of the product ('item') wouldn't be translated properly.
Here's the issue in the admin (edit order) page:
(P.S. I agree as herrvigg said that the Woocommerce file doing all this in PHP is messy, and should be changed to JSON. That's an issue for another time...)

FIX: Translate product name in WC order admin page

---

modules/woo-commerce/qwc-admin.css
modules/woo-commerce/qwc-admin.php

Fixes #804
I'm not sure if this is the best way - adding custom CSS files to each module - but it seems like the most extensible going forwards. I see that the acf module also does this.

Add CSS for language col in WC products page

---

admin/qtx_admin_settings.php

Replaces single underscore function to fix warning in admin language tab

Corrects _() to __()

---

admin/css/qtranslate_configuration.css
admin/qtx_admin_settings_language_list.php
qtranslate.php

New design for the language list:
- icons replace the text descriptions, but those are still available when hovering the icons
- add column for the locale (the one for WordPress, this might evolve)
- add column for the status (filled star = default, empty star = enabled, nothing = disabled)

Redesign language list with icons

---

modules/all-in-one-seo-pack/all-in-one-seo-pack.php
modules/all-in-one-seo-pack/qaioseop-admin.php
modules/events-made-easy/events-made-easy.php
modules/events-made-easy/qeme-admin.php
modules/woo-commerce/qwc-admin.php
modules/woo-commerce/qwc-front.php
modules/woo-commerce/woo-commerce.php

For consistency with the convention in qtranslate, all global functions should start with `qtranxf_`. This is also to avoid any name conflict, thought the risk was already very low with the previous names.
Legacy version definitions are also removed.

Prefix global functions with qtranxf_ in modules

---

admin/qtx_admin.php

Collecting `qtranslate-fields` as `string` on AJAX calls seems to be very specific and I really don't understand the use case.
This was introduced in 3.6.8 as:
> Enhancement: in function qtranxf_collect_translations_posted, parse variables collected as a query string in an option.
The regular collections should take care of all the cases, including AJAX requests.
Why would this query ever be passed as string?
Let's remove this to make the code simpler and we can restore it if really needed. This PR is just to keep track of this removal.

Remove ajax qtranslate-fields collect as string

---

modules/wp-seo/wp-seo-front.php

From #1077 by @Komarovski
> Hello everyone, I've made some frontend fixes for Yoast SEO module that prevent outputting wrong language data in breadcrumbs from indexable tables and also added filters for schema, opengraph and next|prev links.
> 
> Tested on: Wordpress version: 5.8.1 qTranslate XT version: 3.11.0 Yoast SEO version: 17.4

Fix yoast breadcrumbs front

---

modules/acf/src/acf_5/fields/file.php
modules/acf/src/acf_5/fields/image.php
modules/acf/src/acf_5/fields/post_object.php
modules/acf/src/acf_5/fields/text.php
modules/acf/src/acf_5/fields/textarea.php
modules/acf/src/acf_5/fields/url.php
modules/acf/src/acf_5/fields/wysiwyg.php
modules/acf/src/plugin.php

~Localize strings of the ACF module in domain qtranslate (previously in acf).~
~No i18n translations were found in the legacy acf-qtranslate project.~
qTranslate should not add new strings to `acf`.

Fix localization of ACF field labels

---

modules/wp-seo/wp-seo-front.php

Fix - we need to check for "$link_info" not the "$data"

Add Yoast filters for organization schema and publisher

---

modules/gravity-forms/gravity-forms.php

This fixes a notice that is being triggered by updating a Gravity Form choice as an array even though it's a class.
And it will also make sure if it's an object or not (so that legacy versions will keep working).
Before this change on certain PHP versions the following notice will be triggered:
```
Indirect modification of overloaded element of GF_Field_Checkbox has no effect
```

Fixed an issue when trying to translate a GF choice text value

---

modules/slugs/includes/class-qtranslate-slug.php

Use $post->post_title instead of $_POST['post_title']
WordPress 5.0.3/PHP-7.3.1

QTS: Use $post object instead of $_POST array

---

qtranslate_core.php

`setcookie` is function modifying the HTTP header (need to send a `Set-Cookie:`)
sometimes __wp_cron.php__ seems to be the source of headers being sent prematurely
so we avoid setting the cookie during `wp_doing_cron` if the headers have already been sent (it's painless for the plugin to **skip** this)

fix "Headers already sent" error in PHP

---

modules/slugs/includes/class-qtranslate-slug.php
modules/slugs/includes/qtranslate-slug-admin.php
modules/slugs/includes/qtranslate-slug-settings.php

(@herrvigg such small reworks I'm merging directly, pls let me know if you like to review every single commit, no issue my side)

QTS: fixed callback ref/declarations/flush rewrite pos. missed in #1134

---

admin/qtx_admin_gutenberg.php

apply filter to short circuit the Admin handler for Gutenberg.
It is very necessary if you implement your processing for the Gutenberg Block Editor and  the related REST API.
Otherwise, you have to remove each filter and the action separately and sometimes with hacks...

short circuit "QTX_Admin_Gutenberg"

---

admin/qtx_admin_settings.php
modules/qtx_modules_handler.php
qtranslate_core.php

The tab display is independent from its manual activation.
Any module could have extra settings (e.g. ACF).
Make the display dependent on the module state instead.
Add a new `has_settings` field in the module defintions.
Rename `load_modules_enabled` to `load_active_modules`.

Mods: display settings tabs from state

---

admin/qtx_admin_options_update.php

The `bool_elements_array` setting was introduced in #1135 and #1137.
Re-using the QTX_ARRAY code with an extra argument makes it hard
to maintain. The QTX_ARRAY type is not suited for set of checkboxes.
Separate the logic by handling this type all separately.
The `QTX_BOOLEAN_SET` was legacy, defined but not used in the code.
Make the new type generic though only used by `ma_module_enabled`.
Remove the extra `bool_elements_array` argument.

Refactor bool-array setting to `QTX_BOOLEAN_SET`

---

admin/qtx_activation_hook.php
admin/qtx_admin_modules.php
admin/qtx_admin_options.php
admin/qtx_admin_options_update.php
admin/qtx_admin_settings.php
modules/qtx_modules_handler.php
modules/slugs/includes/class-qtranslate-slug.php
modules/slugs/includes/qtranslate-slug-admin.php
qtranslate_core.php
qtranslate_options.php

Disambiguate the confusion between module state and admin options.
* The module state usually depends on other plugin states.
* The admin settings to manually disable or enable the modules are
just admin "preferences" for the module activations.
Changes
* Admin settings (checkboxes)
Make this option admin (previously core) as it's not used on front side.
Rename the `ma_module_enabled` option to `admin_enabled_modules`.
It is saved only from the admin settings and can be deleted at any time.
Make the list display clearer.
* Module state
Rename module _status_ to _state_.
Refactor the module state update to be triggered on various events.
Rename `qtranslate_modules` option to `qtranslate_modules_state`.
The admin enabled settings are only read for the state updates.

Refactor module activation handler and options

---

modules/acf/src/plugin.php
modules/qtx_admin_module.php

Preserve most of the settings API usage in a new module tab.
The option name remains unchanged as `acf_qtranslate`, may evolve.

Integrate ACF settings in modules tab

---

admin/qtx_activation_hook.php
admin/qtx_admin_options.php
admin/qtx_admin_options_update.php
modules/acf/src/plugin.php
modules/qtx_admin_module_manager.php
modules/qtx_admin_module_settings.php
modules/qtx_module_loader.php
modules/slugs/includes/class-qtranslate-slug.php
modules/slugs/includes/qtranslate-slug-admin.php
modules/slugs/includes/qtranslate-slug-settings.php
modules/slugs/slugs.php
qtranslate_options.php

The module custom options are difficult to track due to legacy names.
Make all the name consistent by renaming the old options:
- `acf_qtranslate` -> `qtranslate_module_acf`
- `qts_options` -> `qtranslate_module_slugs`
- `qtranslate_modules` -> `qtranslate_modules_state`
(already pre-renamed in #1150)
Generalize migration and cleanup on plugin activation:
- legacy options belonging to external plugins are preserved and imported
- internal options are renamed from legacy + cleanup.
Create new constants to better keep track the names (e.g. ACF forms) and deletion.
New custom options for modules are updated with `autoload=false`.
Add temporary import for `master`, to be removed before release.

Harmonize module options

---

modules/slugs/includes/class-qtranslate-slug.php

Since 4.8.3, ‘%’ characters will be replaced with a placeholder string with esc_sql().
This fix replaces back the placeholder to ‘%’ after esc_sql() call to retain the original behaviour.

QTS: fix to handle esc_sql() 4.8.3 breaking change

---

modules/slugs/README.md
modules/slugs/includes/class-qtranslate-slug.php

* Fix logic breaking query variables getter in filter_request. Former logic overwrote $query arg with $wp->matched_query. Current one merges the two (preserving possible query vars) only if needed (404 is detected) and removes only the error key.
* Fix language switch links in case of 404 to point to home page instead of current not existing resource.
* Reorder tests and incorporate in single if block
* Add support for utf8 bases (fallback to $wp->request).

QTS: fix query var handling, utf8 bases support

---

modules/slugs/includes/qtranslate-slug-admin.php
modules/woo-commerce/qwc-admin.php

Display the set of QTS slugs when editing (or adding) a WC product attribute.
Hide the regular slug.

WC: fix attribute edit page hidden fields

---

qtranslate_widget.php

There's no need to set hreflang in "a" tag, since we have "link" tags with hreflang in "head" of the website.
I have digged all around the network and didn't find any information about using hreflang attribute inside of "a" tags.

Remove `hreflang` from `a` tag in widget

---

modules/slugs/includes/qtranslate-slug-admin.php

Replace slug fields from WC attribute add/edit admin pages with the link to the relevant existing slugs module settings page.

QTS: remove slug fields for WC attributes add/edit page

---

modules/slugs/includes/class-qtranslate-slug.php

As the information that query is relevant to a page instead of a post is only included in `$wp->matched_query`, merge with `$query` argument must always occur.
If page is identified, `name` key is removed as it is used to retrieve posts instead.
Posts identification test is moved at the end of the block to avoid other conflicts with more specific tests (e.g. custom post types).

QTS: fix conflict pages/posts in filter_request

---

modules/slugs/includes/class-qtranslate-slug.php
modules/slugs/includes/qtranslate-slug-admin.php
modules/slugs/includes/qtranslate-slug-settings.php

Add missing `isset` checks on variables.
Simplify functions where args are not used (e.g. $output OBJECT).
Many minor fixes for better PHP code.

QTS: fix many PHPStorm warnings

---

modules/slugs/admin/slugs-admin.php
modules/slugs/src/slugs-class-slugs.php

The QTS filters come from the legacy plugin:
- filter: `qts_validate_post_slug`
- filter: `qts_validate_term_slug`
- filter: `qts_permastruct`
- filter: `qts_url_args`
For easier maintenance and readability, remove those filters and replace them with direct calls instead.
New `qtranslate` filters will be added on request if the need is justified.
Rename the two `validate` slugs functions to `sanitize` (post/term).
Minor cleanup to improve phpdoc and code readability.

Remove internal QTS filter hooks

---

modules/slugs/src/slugs-class-slugs.php

The WP cache is not appropriated for very short term storage.
Moreover a wrong value could have been stored between different requests.
Replace the cache call with a transient expiring after 30s.
Delete the transient right after reading it.
Rename it to `qtranslate_slugs_matched_page`.

Replace slugs `qts_page_request` cache with transient

---

modules/acf/acf.php
modules/acf/src/acf_5/acf.php
modules/acf/src/acf_5/fields/file.php
modules/acf/src/acf_5/fields/image.php
modules/acf/src/acf_5/fields/post_object.php
modules/acf/src/acf_5/fields/text.php
modules/acf/src/acf_5/fields/textarea.php
modules/acf/src/acf_5/fields/url.php
modules/acf/src/acf_5/fields/wysiwyg.php
modules/acf/src/acf_interface.php
modules/acf/src/plugin.php
modules/gravity-forms/gravity-forms.php
modules/jetpack/jetpack.php
modules/slugs/qtx_module_slugs.php
modules/slugs/slugs.php

Adopt a consistent naming convention with a fixed prefix:
- `QTX_Module_Acf` (several classes)
- `QTX_Module_Gravity_Forms`
- `QTX_Module_Jetpack`
- `QTX_Module_Slugs`
For now use snake case to keep consistent, may evolve later.
Rename the main slugs class file and move it down.

Rename module classes with `QTX_Module` prefix

---

modules/slugs/admin/slugs-admin.php

The slug metaboxes might not be necessary for the woocommerce orders and coupon pages...

Don't show slug metabox on woo shop_orders and shop_coupon pages

---

modules/woo-commerce/qwc-admin.php
modules/woo-commerce/qwc-front.php
modules/woo-commerce/woo-commerce.php

fix unintended translations in webhooks

---

modules/slugs/admin/slugs-admin.php

QTS: replace slugs metabox only if existing

---

qtranslate_core.php
qtranslate_utils.php

Specifically for wp-graphql plugin: https://github.com/wp-graphql/wp-graphql - 3.3k Github stars and 20k active installs.
Add function to check if a request is a GraphQL call, and, if GraphQL call then don't do redirect or set cookies.
Without this change, WPGraphQL does not function correctly. It's default endpoint of /graphql is redirected to /xx/graphql

Add function to check if a request is a GraphQL call.

---

admin/qtx_admin_gutenberg.php

Add default value for qtranslate_admin_block_editor filter based on config post_type_excluded value.
Enhnces work form the merged PR #1112 short circuit "QTX_Admin_Gutenberg"

Add default for qtranslate_admin_block_editor filter

---

modules/slugs/admin/slugs-migrate-qts.php

Fix MySQL error - You can't specify target table 'wp_postmeta' / 'wp_termmeta' for update in FROM clause
#1206

Fix MySQL error #1206

---

modules/slugs/admin/slugs-migrate-qts.php

The previous code worked but `_` is a wildcard for any character in SQL LIKE.
Escape it to make the query more reliable in case the prefix values are changed (for developers).
Ignore other wildcards.

Escape `_` in SQL LIKE queries for Slugs import

---

qtranslate_date_time.php

`strftime` is deprecated in PHP8.1 and should not be used anymore. Add a locale-formatted strftime using `IntlDateFormatter`. This patch is a temporary workaround for immediate PHP8.1 support.
The `strftime` format should be abandonned completely in QTX so it becomes legacy from now. Mark all strftime methods as deprecated for PHPDoc but not for the PHP code yet, until a migration is done.
Attention: QTX uses an extended version of strftime to support extra format tags such as `%q` that are non-standard in strftime.

Replace `strftime` with `IntlDateFormatter` for PHP8.1

---

admin/qtx_activation_hook.php
admin/qtx_admin_utils.php
composer.json
qtranslate.php
qtranslate_date_time.php

The `strftime` function is deprecated in PHP8.1.
Generalize usage of `qtranxf_intl_strftime` for any PHP version. The old implementation is condemned so no point to maintain it. Eventually the strftime may disappear but this requires more work.
Abandon support of ML date-time formats.
The use case is very unclear and looks like very old legacy code. Simplify the code by assuming the format is only for the current lang.
Bump minimal PHP version to 5.5.
Required by `\DateTimeInterface`. Update composer with `ext-int` for `\IntlDateFormatter`.
Deprecations -> new versions
- `qtranxf_strftime` -> `qtranxf_intl_strftime`
- `qtranxf_convertFormat` -> `qtranxf_convert_to_strftime_format_using_config`. 
- `qtranxf_convertTimeFormat` -> `qtranxf_get_language_config_date_time`.
- …

Refactor date-time conversions using `qtranxf_intl_strftime`

---

admin/css/qtranslate_configuration.css
admin/qtx_admin.php
admin/qtx_admin_settings.php
qtranslate_options.php

Relates to #1234.
The "override" date/time options are too confusing. If a user ask for a specific format it should never be overriden. The use case would only be for debug, but not for the end-user. We might add new options to disable the translation or replace the current language format with a default value, but that is out of scope for the current "override" values.
Improve the CSS styles for deprecated options with two levels.

Deprecate date/strftime "override" options

---

admin/qtx_admin_settings.php
qtranslate_date_time.php
qtranslate_hooks.php
qtranslate_options.php

The `strftime` function is deprecated in PHP8.1 but the legacy language formats are still maintained with `IntlDateFormatter` (#1228, #1238). The strftime format used in the qTranslate language options should be deprecated (#1234). The date format should also be refactored without intermediate legacy conversions.
Meanwhile, it is safer to add a fallback option to disable any date/time conversion and hooks in qTranslate in case something unexpected would happen. This option could be enough for some users. The standard WP behavior for `the_time()` and all filters with `get_post_modified_time` is translating the global date/time WP formats. However when calling functions like `get_post_time()` from the code without any argument, no translation is done which could be unexpected when using …

Add date/time option to use WP and ignore QTX formats

---

src/modules/acf/fields/file.php
src/modules/acf/fields/image.php
src/modules/acf/fields/post_object.php
src/modules/acf/fields/text.php
src/modules/acf/fields/textarea.php
src/modules/acf/fields/url.php
src/modules/acf/fields/wysiwyg.php
src/modules/acf/register.php

ACF code is unnecessarily duplicated for the initialization.
Re-use `parent` methods for constructor and `initialize`.
Define ACF_CATEGORY_QTX for the category ID.

Refactor ACF init of qTranslate fields

---

src/modules/acf/admin.php

Eventually the extended types may be removed completely.
This new feature allows to choose which extended types can be picked.
The default value becomes false for all extended types.
This only impacts the list of types available in the group edit.
The extended types are still loaded and translated as usual. It is up to the admin to clean up pending types.

Add new ACF settings to select extended `qTranslate` types

---

src/init.php

This legacy filter should be named with a `qtranslate` prefix. It is not well designed.
The intention was to allow third-party integration of a custom Translator class using the i18n interface but there is no practical way to change it.
Deprecate this filter, to be removed in next major release. If there is a real need it should be done differently.

Deprecate `wp_translator` filter

---

src/modules/acf/admin.php
src/modules/acf/fields/text.php
src/modules/acf/fields/textarea.php
src/modules/acf/fields/wysiwyg.php

Follow-up of #1186 and #1300.
Since the standard ACF fields are better supported, those should be preferred over the qTranslate extended fields.
In particular: `text`, `textarea`, `wysiwyg` are covered by the ACF standard fields, while others only exist as qTranslate extended fields.
Deprecate softly these "duplicated" extended fields in their labels.

Deprecate ACF-qTranslate `text/textarea/wysiwyg` extended fields

---

src/modules/acf/admin.php
src/modules/acf/extended.php
src/modules/acf/fields/file.php
src/modules/acf/fields/image.php
src/modules/acf/fields/post_object.php
src/modules/acf/fields/text.php
src/modules/acf/fields/textarea.php
src/modules/acf/fields/url.php
src/modules/acf/fields/wysiwyg.php
src/modules/acf/loader.php

ACF before 5.6.0 requires a special handling for `initialize()` methods in extended fields.
Require ACF minimal version 5.6.0 to simplify the code and delete the constructors.
Rename `QTX_Module_Acf_Register` to `QTX_Module_Acf_Extended` and make it mostly static.

Bump ACF minimal version 5.6.0

---

qtranslate.php
src/admin/admin.php
src/admin/admin_options.php
src/admin/admin_options_update.php
src/admin/admin_utils.php
src/admin/update_gettext_db.php
src/date_time.php
src/deprecated.php
src/init.php
src/language_blocks.php
src/options.php

These functions do not carry the logical load of the code in the files.
In the future, these functions will have to be removed

Moved deprecated functions to a separate file.

---

src/admin/activation_hook.php
src/admin/admin.php
src/admin/admin_options_update.php
src/admin/admin_settings.php
src/admin/admin_settings_language_list.php
src/admin/admin_utils_db.php
src/admin/block_editor.php
src/date_time.php
src/frontend.php
src/language_blocks.php
src/modules/slugs/admin_migrate_qts.php
src/options.php
src/taxonomy.php
src/url.php

Use null coalesce operator.
Remove unnecessary checks and references.
Refactor `select_raw_response_language` for each raw entry.
Refactor `qtranxf_excludeUntranslatedPosts` without fake `while` loop.
Misc improvements.

Lint PHP by simplifying expressions

---

src/language_blocks.php

All filters of qTranslate-XT should have a `qtranslate` suffix.
Rename to `qtranslate_content_translation_not_available`.
Deprecate the previous one, to be removed in next major release.

Rename `i18n_content_translation_not_available` filter

---

dev/qtx-tests.php
src/class_translator.php
src/translator_interface.php

All filters of qTranslate-XT should have a `qtranslate` suffix. Rename to `qtranslate_{item}`.
These filters are never used internally.
This class was meant to facilitate 3rd-party integration but it doesn't feel justified anymore, as developers are more inclined to call `qtranxf_use*` functions directly.
Before removing that class the official API should be clarified.

Rename `QTX_Translator::translate_{item}`  filters

---

src/modules/slugs/slugs.php

Bunch of fixes for slugs module:
- Slugs: fix possible null passed to filter_request functions
Fixes #1358 
- Slugs: filter_request() reformatting and cleanup
- Slugs: use 'Locale at front-end' if available as hreflang
Fixes #1359 
- Slugs: remove reference to obsolete hook
- Slugs: fix home_url to handle 'rest' and 'relative' schemes
This is needed to fix wrong result in case of 'relative' scheme argument request, being currently returned the entire 'http/https' anyways.
Fixes #1373 
Fixes #1273
- Slugs: restore original query if filter_request() fails
In case filter_request is not able to identify an handling function, original query needs to be provided (including the 404 flag previously stripped)

[SLUGS] misc fixes

---

src/modules/slugs/slugs.php

prevent warning on Woocommerce special product archive page when using the product filter

[SLUGS] fix warning on post_type missing key

---

src/modules/slugs/README.md

Some extra instructions to migrate Slugs from the legacy plugin, after having some issues and getting help from one of the maintaners, @spleen1981.
Discussion can be followed here: https://github.com/qtranslate/qtranslate-xt/discussions/1401#discussioncomment-8950469

Detailed instructions to migrate Slugs from legacy

---

qtranslate.php

As mentioned in qtranslate/qtranslate-xt#1344 the plugin is incompatible with wp-cli.
For example, the following command fails:
wp-cli plugin activate qtranslate-xt
Any action with wp-cli results in an error such as the one below, where functions haven't been defined.
call_user_func(): Argument #1 ($callback) must be a valid callback
In my case the missing function happened to be `function "qtranxf_default_default_language" not found`.
The reason for this, is the functions were defined in `/src/admin/activation_hook.php` which isn't included when the WP function `is_admin()` returns false, as it does in wp-cli. Any user who has access to the wp-cli binary clearly has administrative privileges over the installation, so not including those function definitions is presumably not the intended …

Fix wp-cli incompatibility 

---

README.md
composer.json
qtranslate.php
readme.txt
src/admin/activation_hook.php
src/language_detect.php

The recommended version becomes PHP 8.4.
PHP 7.4 has reached end of life support in 2022.
PHP 8.0 has reached end of life support in 2023.
The short-term goal is to bump to minimum PHP 8.1 gradually.

Bump PHP minimum requirement to 7.3

---

src/admin/admin_settings.php
src/modules/admin_module.php
src/modules/admin_module_settings.php

The text domain should not be used before the `init` event.
The admin module settings need to be loaded before this, so we have
to remove all text translations from that sequence.

Fix `_load_textdomain_just_in_time` notice (#1433) 
